job_specifications:
- id: namdjob
  auto_complete: true
  tasks:
  - docker_image: alfpark/namd:2.11-tcp
    additional_docker_run_options:
    - --net=host
    multi_instance:
      num_instances: pool_current_dedicated
    command: /sw/run_namd.sh apoa1 100
